
/// Webpage design schema

import React, { useState, useEffect, useRef } from 'react';
import { 
  Settings, 
  Play, 
  Download, 
  Square, 
  Code2, 
  Loader2, 
  CheckCircle2,
  FileCode,
  AlertCircle
} from 'lucide-react';
import { Toaster, toast } from 'sonner';

import { Button } from "./components/ui/button";
import { Input } from "./components/ui/input";
import { Label } from "./components/ui/label";
import { Textarea } from "./components/ui/textarea";
import { 
  Card, 
  CardContent, 
  CardDescription, 
  CardFooter, 
  CardHeader, 
  CardTitle 
} from "./components/ui/card";
import { Progress } from "./components/ui/progress";
import { 
  Collapsible, 
  CollapsibleContent, 
  CollapsibleTrigger 
} from "./components/ui/collapsible";
import { Alert, AlertDescription, AlertTitle } from "./components/ui/alert";

// Mock function to simulate API call
const generateCode = async (prompt: string, signal: AbortSignal) => {
  return new Promise<string>((resolve, reject) => {
    const timeout = setTimeout(() => {
      resolve(`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Generated Landing Page</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-slate-50 text-slate-900 font-sans antialiased">
    <div class="max-w-4xl mx-auto px-6 py-12">
        <header class="mb-12 text-center">
            <h1 class="text-4xl font-bold tracking-tight mb-4 text-indigo-600">Welcome to Your App</h1>
            <p class="text-lg text-slate-600">Generated based on prompt: "${prompt}"</p>
        </header>
        <main class="bg-white rounded-xl shadow-sm border border-slate-200 p-8">
            <h2 class="text-2xl font-semibold mb-4">Content Section</h2>
            <p class="text-slate-600 mb-6">This is a placeholder for the content generated by the Braze Agent.</p>
            <div class="grid gap-4 md:grid-cols-2">
                <div class="p-4 bg-indigo-50 rounded-lg">
                    <h3 class="font-medium text-indigo-900 mb-2">Feature One</h3>
                    <p class="text-sm text-indigo-700">Description of feature one goes here.</p>
                </div>
                <div class="p-4 bg-indigo-50 rounded-lg">
                    <h3 class="font-medium text-indigo-900 mb-2">Feature Two</h3>
                    <p class="text-sm text-indigo-700">Description of feature two goes here.</p>
                </div>
            </div>
            <div class="mt-8 text-center">
                <button class="px-6 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition">Call to Action</button>
            </div>
        </main>
        <footer class="mt-12 text-center text-slate-500 text-sm">
            &copy; ${new Date().getFullYear()} Generated App. All rights reserved.
        </footer>
    </div>
</body>
</html>`);
    }, 3000); // 3 seconds simulation

    signal.addEventListener('abort', () => {
      clearTimeout(timeout);
      reject(new DOMException('Aborted', 'AbortError'));
    });
  });
};

export default function App() {
  const [apiKey, setApiKey] = useState('');
  const [endpoint, setEndpoint] = useState('');
  const [prompt, setPrompt] = useState('');
  const [isSettingsOpen, setIsSettingsOpen] = useState(true);
  
  const [status, setStatus] = useState<'idle' | 'generating' | 'completed' | 'error'>('idle');
  const [progress, setProgress] = useState(0);
  const [generatedCode, setGeneratedCode] = useState<string | null>(null);
  
  const abortControllerRef = useRef<AbortController | null>(null);

  // Reset progress when idle
  useEffect(() => {
    if (status === 'idle') {
      setProgress(0);
    }
  }, [status]);

  // Simulate progress
  useEffect(() => {
    let interval: NodeJS.Timeout;
    if (status === 'generating') {
      interval = setInterval(() => {
        setProgress((prev) => {
          if (prev >= 90) return prev; // Hold at 90% until complete
          return prev + 5;
        });
      }, 150);
    }
    return () => clearInterval(interval);
  }, [status]);

  const handleGenerate = async () => {
    if (!apiKey || !endpoint) {
      toast.error("Missing Configuration", {
        description: "Please provide your Braze API Key and SDK Endpoint."
      });
      setIsSettingsOpen(true);
      return;
    }
    if (!prompt.trim()) {
      toast.error("Empty Prompt", {
        description: "Please describe what you want to generate."
      });
      return;
    }

    setStatus('generating');
    setGeneratedCode(null);
    abortControllerRef.current = new AbortController();

    try {
      const code = await generateCode(prompt, abortControllerRef.current.signal);
      setGeneratedCode(code);
      setStatus('completed');
      setProgress(100);
      toast.success("Generation Complete", {
        description: "Your landing page code is ready to download."
      });
    } catch (error) {
      if (error instanceof DOMException && error.name === 'AbortError') {
        setStatus('idle');
        toast.info("Generation Stopped", {
          description: "The process was cancelled by user."
        });
      } else {
        setStatus('error');
        toast.error("Generation Failed", {
          description: "Something went wrong. Please try again."
        });
      }
    }
  };

  const handleStop = () => {
    if (abortControllerRef.current) {
      abortControllerRef.current.abort();
    }
  };

  const handleDownload = () => {
    if (!generatedCode) return;
    
    const blob = new Blob([generatedCode], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'landing-page.html';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast.success("Download Started", {
      description: "landing-page.html has been saved."
    });
  };

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 font-sans selection:bg-indigo-100 selection:text-indigo-900">
      <Toaster position="top-center" />
      
      {/* Header */}
      <header className="sticky top-0 z-50 w-full border-b bg-white/80 backdrop-blur supports-[backdrop-filter]:bg-white/60">
        <div className="container flex h-14 max-w-screen-lg items-center px-4 mx-auto">
          <div className="flex items-center gap-2 font-semibold">
            <div className="rounded-md bg-indigo-600 p-1">
              <Code2 className="h-5 w-5 text-white" />
            </div>
            <span>Braze Agent</span>
          </div>
          <div className="ml-auto flex items-center gap-2">
            <span className="text-xs text-muted-foreground hidden sm:inline-block">v1.0.0</span>
          </div>
        </div>
      </header>

      <main className="container max-w-screen-md mx-auto py-10 px-4 space-y-8">
        
        {/* Intro Text */}
        <div className="text-center space-y-2 mb-8">
          <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Generate Custom Landing Pages</h1>
          <p className="text-muted-foreground text-lg">
            Enter your Braze credentials and describe your desired page. The agent will handle the rest.
          </p>
        </div>

        {/* Configuration Panel */}
        <Card className="border-slate-200 shadow-sm overflow-hidden">
          <Collapsible open={isSettingsOpen} onOpenChange={setIsSettingsOpen}>
            <div className="flex items-center justify-between px-6 py-4 bg-slate-50/50">
              <div className="flex items-center gap-2">
                <Settings className="h-4 w-4 text-indigo-600" />
                <h3 className="font-medium text-sm text-slate-700">Configuration</h3>
              </div>
              <CollapsibleTrigger asChild>
                <Button variant="ghost" size="sm" className="h-8 w-8 p-0">
                  <span className="sr-only">Toggle settings</span>
                  <Settings className={`h-4 w-4 transition-transform ${isSettingsOpen ? 'rotate-180' : ''}`} />
                </Button>
              </CollapsibleTrigger>
            </div>
            
            <CollapsibleContent>
              <CardContent className="space-y-4 pt-4 border-t border-slate-100">
                <div className="grid gap-4 md:grid-cols-2">
                  <div className="space-y-2">
                    <Label htmlFor="apiKey">Braze API Key</Label>
                    <Input 
                      id="apiKey" 
                      type="password" 
                      placeholder="Input your Braze API Key" 
                      value={apiKey}
                      onChange={(e) => setApiKey(e.target.value)}
                      className="font-mono text-sm"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="endpoint">Braze SDK Endpoint</Label>
                    <Input 
                      id="endpoint" 
                      placeholder="https://sdk.iad-01.braze.com" 
                      value={endpoint}
                      onChange={(e) => setEndpoint(e.target.value)}
                      className="font-mono text-sm"
                    />
                  </div>
                </div>
              </CardContent>
            </CollapsibleContent>
          </Collapsible>
        </Card>

        {/* Prompt Section */}
        <Card className="border-slate-200 shadow-md">
          <CardHeader>
            <CardTitle>Prompt</CardTitle>
            <CardDescription>
              Describe the landing page you want to generate. Be specific about the layout, colors, and content.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Textarea 
              placeholder="Example: Create a modern landing page for a coffee shop with a hero section, a menu grid, and a newsletter signup form. Use warm brown tones."
              className="min-h-[150px] resize-y text-base"
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              disabled={status === 'generating'}
            />
          </CardContent>
          <CardFooter className="flex justify-between items-center border-t bg-slate-50/50 px-6 py-4">
            <div className="text-xs text-muted-foreground">
              {status === 'generating' ? (
                <span className="flex items-center gap-2 text-indigo-600 font-medium">
                  <Loader2 className="h-3 w-3 animate-spin" />
                  Generating code...
                </span>
              ) : status === 'completed' ? (
                <span className="flex items-center gap-2 text-green-600 font-medium">
                  <CheckCircle2 className="h-3 w-3" />
                  Ready to download
                </span>
              ) : (
                <span>Ready for input</span>
              )}
            </div>

            <div className="flex gap-2">
              {status === 'generating' ? (
                <Button 
                  variant="destructive" 
                  onClick={handleStop}
                  className="gap-2"
                >
                  <Square className="h-4 w-4" fill="currentColor" />
                  Stop Generation
                </Button>
              ) : (
                <Button 
                  onClick={handleGenerate} 
                  disabled={status === 'generating'}
                  className="bg-indigo-600 hover:bg-indigo-700 text-white gap-2 shadow-sm transition-all hover:shadow-md"
                >
                  <Play className="h-4 w-4" fill="currentColor" />
                  Generate Landing Page
                </Button>
              )}
            </div>
          </CardFooter>
        </Card>

        {/* Progress / Status Area */}
        {status === 'generating' && (
          <div className="space-y-2 animate-in fade-in slide-in-from-bottom-2 duration-300">
             <div className="flex justify-between text-sm text-muted-foreground">
                <span>Processing prompt...</span>
                <span>{progress}%</span>
             </div>
             <Progress value={progress} className="h-2" />
          </div>
        )}

        {/* Result Area */}
        {status === 'completed' && (
          <Card className="border-green-200 bg-green-50/30 animate-in fade-in slide-in-from-bottom-4 duration-500">
            <CardContent className="pt-6">
              <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
                <div className="flex items-center gap-4">
                  <div className="p-3 bg-green-100 rounded-full">
                    <FileCode className="h-6 w-6 text-green-700" />
                  </div>
                  <div>
                    <h3 className="font-semibold text-green-900">Code Generated Successfully</h3>
                    <p className="text-sm text-green-700">Your HTML file is ready for use.</p>
                  </div>
                </div>
                <Button 
                  onClick={handleDownload}
                  className="w-full sm:w-auto border-green-200 bg-white text-green-700 hover:bg-green-50 hover:text-green-800 hover:border-green-300 gap-2 shadow-sm"
                  variant="outline"
                >
                  <Download className="h-4 w-4" />
                  Download Code File
                </Button>
              </div>
            </CardContent>
          </Card>
        )}
        
        {status === 'error' && (
           <Alert variant="destructive" className="animate-in fade-in slide-in-from-bottom-2">
            <AlertCircle className="h-4 w-4" />
            <AlertTitle>Error</AlertTitle>
            <AlertDescription>
              There was an issue generating your code. Please check your inputs and try again.
            </AlertDescription>
          </Alert>
        )}

      </main>
      
      <footer className="border-t py-6 mt-12 bg-white">
         <div className="container max-w-screen-lg mx-auto px-4 text-center text-sm text-muted-foreground">
            <p>Powered by Braze Agent Technology</p>
         </div>
      </footer>
    </div>
  );
}
